### ISSUE TITLE
Suspicious results

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#47]
This could very well be due to a lack of understanding on my end, but the attached "Average Monthly Energy Production" results are very suspicious:
![Average Monthly Energy Production](https://user-images.githubusercontent.com/14652512/154820781-8cd34abe-a3b8-4a42-bb39-417f53b42304.png)

Why would the average realization from `pvrpm` result in an approximately three-fold increase in energy production compared to the SAM base case?

I've attached my configuration and json files as well as my `poetry.lock` file (contains versions of all packages in my environment) for reproducibility:
[richland.zip](https://github.com/FSEC-Photovoltaics/pvrpm-lcoe/files/8103078/richland.zip)

**Comment by brandons209** [comment]
You know I've actually seen this before and my professor and I tried figuring it out. I'm fairly certain we figured it to be a quirk of SAM and not PVRPM, but I will take another look at this since it is odd.

**Comment by brandons209** [comment]
Alright I remember now and reconfirmed. So this is expected behavior. The reason this is low is because the base case has no failures, but the modules still degrade every year. So for this graph monthly energy is averaged across the lifetime of the simulation and the base case has lower energy since degraded modules in the later years generate much less power and bring the overall average dow
![Average Monthly Energy Production](https://user-images.githubusercontent.com/16628799/155830308-d9572fa4-67f8-426a-816c-923efc07cf41.png)
n. In the realizations, modules fail and are replace so their degradation gets reset and therefore operate at peak efficiency, resulting in overall more energy generated per month. You see this very clearly with small systems, but in large systems with thousands of modules you wouldn't see this graph. 

For reference, this is what the graph would look like for your case if the base case had no degradation for the modules.

**Comment by blthayer** [comment]
Thank you for the explanation, @brandons209!
